#include<bits/stdc++.h>
using namespace std;
#define int long long

#define _Life_s_For_The_Living__by_Passenger_Well_grey_clouds_wrapped void 
#define round_the_town_like_elastic_Cars_stood_like_toys_made solve() 
#define of_Taiwanese_plastic_The_boy_laughed_at_the_spastic_dancing { 
#define around_in_the_rain_While_laundrettes_cleaned_clothes__high_heals int 
#define rub_toes_Puddles_splashed_huddles_of_bus_stop_crows_Dressed n,x; 
#define in_their_suits_and_their_boots_well_they_all_look cin>>n>>x; 
#define the_same_I_took_myself_down_to_the_cafe_to int 
#define find_all_the_boys_lost_in_books_and_crackling_vinyl a[n]; 
#define And_carved_out_a_poem_above_the_urinal_that_read for(int 
#define Don_t_you_cry_for_the_lost_Smile_for_the_living i=0; 
#define Get_what_you_need_and_give_what_you_re_given_Life_s i<n; 
#define for_the_living_so_live_it_Or_you_re_better_off i++) 
#define dead_While_the_evening_pulled_the_moon_out_of_it_s cin>>a[i]; 
#define packet_Stars_shone_like_buttons_on_an_old_man_s_jacket sort(a,a+n,greater<int>()); 
#define We_needed_a_nail_but_we_tacked_it__til_it int 
#define fell_of_the_wall_While_pigeon_s_pecked_trains__sparks_flew i; 
#define like_planes_The_rain_showed_the_rainbows_in_the_oil double 
#define stains_And_we_all_had_new_iPhones_but_no_one s=0.0; 
#define had_no_one_to_call_And_I_stumbled_down_to for(i=0; 
#define the_stomach_of_the_town_Where_the_widow_takes_memories i<n; 
#define to_slowly_drown_With_a_hand_to_the_sky_and i++) 
#define a_mist_in_her_eye_she_said_Don_t_you_cry { 
#define for_the_lost_Smile_for_the_living_Get_what_you s+=a[i]; 
#define need_and_give_what_you_re_given_Life_s_for_the_living if(s/(double)(i+1)<x) 
#define so_live_it_Or_you_re_better_off_dead_Well_I_m break; 
#define sick_of_this_town__this_blind_man_s_forage_They_take } 
#define your_dreams_down_and_stick_them_in_storage_You_can cout<<i<<endl; 
#define have_them_back_son_when_you_ve_paid_off_your_mortgage } 
#define and_loans_Oh_hell_with_this_place__I_ll_go_it int32_t 
#define my_own_way_I_ll_stick_out_my_thumb_and_I main() 
#define trudge_down_the_highway_Someday_someone_must_be_going_my { 
#define way_home_Till_then_I_ll_make_my_bed_from_a int 
#define disused_car_With_a_mattress_of_leaves_and_a_blanket t; 
#define of_stars_And_I_ll_stitch_the_words_into_my_heart cin>>t; 
#define with_a_needle_and_thread_Don_t_you_cry_for_the while(t--) 
#define lost_Smile_for_the_living_Get_what_you_need_and { 
#define give_what_you_re_given_You_know_life_s_for_the_living solve(); 
#define so_live_it_Or_you_re_better_off_dead_Don_t_you } 
#define cry_for_the_lost_Smile_for_the_living_Get_what_you_need_and_give_what_you_re_given_Life_s_for_the_living_so_live_it_Or_you_re_better_off_dead } 

_Life_s_For_The_Living__by_Passenger_Well_grey_clouds_wrapped round_the_town_like_elastic_Cars_stood_like_toys_made of_Taiwanese_plastic_The_boy_laughed_at_the_spastic_dancing around_in_the_rain_While_laundrettes_cleaned_clothes__high_heals rub_toes_Puddles_splashed_huddles_of_bus_stop_crows_Dressed 
in_their_suits_and_their_boots_well_they_all_look the_same_I_took_myself_down_to_the_cafe_to find_all_the_boys_lost_in_books_and_crackling_vinyl And_carved_out_a_poem_above_the_urinal_that_read Don_t_you_cry_for_the_lost_Smile_for_the_living 
Get_what_you_need_and_give_what_you_re_given_Life_s for_the_living_so_live_it_Or_you_re_better_off dead_While_the_evening_pulled_the_moon_out_of_it_s packet_Stars_shone_like_buttons_on_an_old_man_s_jacket We_needed_a_nail_but_we_tacked_it__til_it 
fell_of_the_wall_While_pigeon_s_pecked_trains__sparks_flew like_planes_The_rain_showed_the_rainbows_in_the_oil stains_And_we_all_had_new_iPhones_but_no_one had_no_one_to_call_And_I_stumbled_down_to the_stomach_of_the_town_Where_the_widow_takes_memories 
to_slowly_drown_With_a_hand_to_the_sky_and a_mist_in_her_eye_she_said_Don_t_you_cry for_the_lost_Smile_for_the_living_Get_what_you need_and_give_what_you_re_given_Life_s_for_the_living so_live_it_Or_you_re_better_off_dead_Well_I_m 
sick_of_this_town__this_blind_man_s_forage_They_take your_dreams_down_and_stick_them_in_storage_You_can have_them_back_son_when_you_ve_paid_off_your_mortgage and_loans_Oh_hell_with_this_place__I_ll_go_it my_own_way_I_ll_stick_out_my_thumb_and_I 
trudge_down_the_highway_Someday_someone_must_be_going_my way_home_Till_then_I_ll_make_my_bed_from_a disused_car_With_a_mattress_of_leaves_and_a_blanket of_stars_And_I_ll_stitch_the_words_into_my_heart with_a_needle_and_thread_Don_t_you_cry_for_the 
lost_Smile_for_the_living_Get_what_you_need_and give_what_you_re_given_You_know_life_s_for_the_living so_live_it_Or_you_re_better_off_dead_Don_t_you cry_for_the_lost_Smile_for_the_living_Get_what_you_need_and_give_what_you_re_given_Life_s_for_the_living_so_live_it_Or_you_re_better_off_dead 
